/*
 * Copyright (c) 2017-2019, The Linux Foundation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#define CONFIG_SND_SOC_MDM9607 1
#define CONFIG_MSM_ADSP_LOADER 1
#define CONFIG_MSM_SECURE_BUFFER 1
#define CONFIG_SND_SOC_QDSP6V2 1
#define CONFIG_SND_SOC_MSM_QDSP6V2_INTF 1
#define CONFIG_SND_SOC_MSM_STUB 1
#define CONFIG_SND_SOC_WCD9330 1
#define CONFIG_SND_SOC_MSM_HOSTLESS_PCM 1
#define CONFIG_MSM_QDSP6_APRV3_RPMSG 1
#define CONFIG_MSM_ADSP_LOADER 1
#define CONFIG_MSM_QDSP6V2_CODECS 1
#define CONFIG_WCD9330_CODEC 1
#define CONFIG_ION_MSM 1
#define CONFIG_SND_SOC_WCD9XXX 1
#define CONFIG_SND_HWDEP 1
#define CONFIG_QTI_PP 1
#define CONFIG_MSM_CDC_PINCTRL 1
#define CONFIG_SND_SOC_WCD_CPE 1
#define CONFIG_WCD9XXX_CODEC_CORE 1
#define CONFIG_SND_HWDEP_ROUTING 1

#define CONFIG_PRI_SEC_RX_TX_DISABLE 1
#define CONFIG_SLIMBUS_DISABLE 1
#define CONFIG_WSA_CDC_DISABLE 1
#define CONFIG_RX_CDC_DISABLE 1
#define CONFIG_HDMI_DISABLE 1
#define CONFIG_DISPLAY_PORT_DISABLE 1
#define CONFIG_SPDIF_DISABLE 1
#define CONFIG_USB_AUDIO_RX_DISABLE 1
#define CONFIG_MI2S_DISABLE 1
#define CONFIG_QUAT_MI2S_DISABLE 1
#define CONFIG_TERT_MI2S_DISABLE 1
#define CONFIG_SEC_MI2S_DISABLE 1
#define CONFIG_INT_MI2S_DISABLE 1
#define CONFIG_QUIN_MI2S_DISABLE 1
#define CONFIG_TDM_DISABLE 1
#define CONFIG_MULTIMEDIA3_DISABLE 1
#define CONFIG_MULTIMEDIA4_DISABLE 1
#define CONFIG_MULTIMEDIA8_DISABLE 1
#define CONFIG_MULTIMEDIA9_DISABLE 1
#define CONFIG_MULTIMEDIA10_DISABLE 1
#define CONFIG_MULTIMEDIA16_DISABLE 1
#define CONFIG_MULTIMEDIA17_DISABLE 1
#define CONFIG_MULTIMEDIA18_DISABLE 1
#define CONFIG_MULTIMEDIA19_DISABLE 1
#define CONFIG_MULTIMEDIA20_DISABLE 1
#define CONFIG_MULTIMEDIA21_DISABLE 1
#define CONFIG_MULTIMEDIA27_DISABLE 1
#define CONFIG_MULTIMEDIA28_DISABLE 1
#define CONFIG_MULTIMEDIA29_DISABLE 1
#define CONFIG_INTERNAL_A2DP_DISABLE 1
#define CONFIG_AUX_PCM_DISABLE 1
#define CONFIG_EC_REF_DISABLE 1
#define CONFIG_UNUSED_VOICE_MIXERS_DISABLE 1
#define CONFIG_LSM_DISABLE 1
#define CONFIG_STUB_DISABLE 1
